name: flutter_heatmap_calendar_plus
description: Flutter heatmap calendar inspired by github contribution chart which includes traditional mode / calendar mode.
version: 1.0.5
homepage: https://github.com/shehzadraheem/flutter_heatmap_calendar_plus.git

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
